server:
  port: 8080
spring:
  application:
    name: faaps-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/faaps?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:faaps}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
